# Project information

site_name: Protecting Workloads With AWS WAF, Amazon Inspector and AWS Systems Manager
site_description: This workshop shows how you can protect a web site using AWS Security Services
site_author: 'aws-security-workshops@amazon.com'
site_url: 'https://protecting-workloads.awssecworkshops.com/'

# Repository
repo_name: 'aws-samples/protecting-workloads-workshop'
repo_url: 'https://github.com/aws-samples/protecting-workloads-workshop'

# Copyright
copyright: '&copy; 2019, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/aws_smile_logo.png'
  favicon: 'assets/images/aws-favicon.ico'
  feature:
    tabs: true
  custom_dir: 'docs/theme'

# Customization
extra_css:
  - 'stylesheets/custom.css'
extra_javascript:
  - 'javascripts/extra.js'
extra:
  social:
    - type: 'home'
      link: 'http://protecting-workloads.awssecworkshops.com/'
    - type: 'shield'
      link: 'https://aws.amazon.com/security/'
    - type: 'twitter'
      link: 'https://twitter.com/awssecurityinfo?lang=en'
    - type: 'rss'
      link: 'https://aws.amazon.com/blogs/security/'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details

# Navigation
nav:
  - Home: 'index.md'
  - Workshop:
    - Scenario: 'workshop/index.md'
    - Getting Started: 'workshop/getting-started.md'
    - Perimeter Layer:
      - 'Build Phase': 'workshop/perimeter-layer/build.md'
      - 'Assess Phase': 'workshop/perimeter-layer/assess.md'
      - 'Remediate Phase': 'workshop/perimeter-layer/remediate.md'
      - 'Verify Phase': 'workshop/perimeter-layer/verify.md'
    - Host Layer:
      - 'Build Phase': 'workshop/host-layer/build.md'
      - 'Assess Phase': 'workshop/host-layer/assess.md'
      - 'Remediate Phase': 'workshop/host-layer/remediate.md'
      - 'Verify Phase': 'workshop/host-layer/verify.md'
    - Cleanup: 'workshop/cleanup.md'
  - Builder Session:
    - Scenario: 'builder-session/index.md'
    - Getting Started: 'builder-session/getting-started.md'
    - Build Phase: 'builder-session/build.md'
    - Assess Phase: 'builder-session/assess.md'
    - Remediate Phase: 'builder-session/remediate.md'
    - Verify Phase: 'builder-session/verify.md'
    - Cleanup Phase: 'builder-session/cleanup.md'
  - Contributing: 'contribute.md'
  - License: 'license.md'
# - Workshop (Test Version):
#   - Scenario: 'workshoptest/index.md'
#   - Getting Started: 'workshoptest/getting-started.md'
#   - Perimeter Layer:
#     - 'Build Phase': 'workshoptest/perimeter-layer/build.md'
#     - 'Assess Phase': 'workshoptest/perimeter-layer/assess.md'
#     - 'Remediate Phase': 'workshoptest/perimeter-layer/remediate.md'
#     - 'Verify Phase': 'workshoptest/perimeter-layer/verify.md'
#     - 'Cleanup Phase': 'workshoptest/perimeter-layer/cleanup.md'
#   - Host Layer:
#     - 'Build Phase': 'workshoptest/host-layer/build.md'
#     - 'Assess Phase': 'workshoptest/host-layer/assess.md'
#     - 'Remediate Phase': 'workshoptest/host-layer/remediate.md'
#     - 'Verify Phase': 'workshoptest/host-layer/verify.md'
#     - 'Cleanup Phase': 'workshoptest/host-layer/cleanup.md'
#   - Cleanup: 'workshoptest/cleanup.md'
# - Builder Session (Test Version):
#   - Scenario: 'builder-session-test/index.md'
#   - Getting Started: 'builder-session-test/getting-started.md'
#   - Build Phase: 'builder-session-test/build.md'
#   - Assess Phase: 'builder-session-test/assess.md'
#   - Remediate Phase: 'builder-session-test/remediate.md'
#   - Verify Phase: 'builder-session-test/verify.md'
#   - Cleanup Phase: 'builder-session-test/cleanup.md'
